In [3]:
# lib:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [5]:
dataset=pd.read_csv('Data.csv') # read_data

In [6]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
dataset.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [8]:
type(dataset)

pandas.core.frame.DataFrame

In [9]:
dataset['Salary'].fillna(dataset['Salary'].groupby(dataset['Country']).transform('mean'),inplace=True)

In [10]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  68500.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [11]:
dataset['Age'].fillna(dataset['Age'].groupby(dataset['Country']).transform('mean'),inplace=True)

In [12]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  68500.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  32.5  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [13]:
x=dataset.iloc[:,0:3].values
y=dataset.iloc[:,3].values

In [6]:
x,y

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
       dtype=object))

In [3]:
# Encoding categorical data
# Encoding the independent variable
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [7]:
labelencoder_x=LabelEncoder()
x[:,0]=labelencoder_x.fit_transform(x[:,0])

In [30]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 68500.0],
       [0, 35.0, 58000.0],
       [2, 32.5, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [31]:
onehotencoder=OneHotEncoder(categorical_features=[0])
x=onehotencoder.fit_transform(x).toarray()

In [32]:
x

array([[1.00e+00, 0.00e+00, 0.00e+00, 4.40e+01, 7.20e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.70e+01, 4.80e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.00e+01, 5.40e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.80e+01, 6.10e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.00e+01, 6.85e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.50e+01, 5.80e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.25e+01, 5.20e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.80e+01, 7.90e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.00e+01, 8.30e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.70e+01, 6.70e+04]])

In [34]:
labelencoder_y=LabelEncoder()
y[:]=labelencoder_y.fit_transform(y[:])

# labelencoder_y=LabelEncoder()
# y=labelencoder_y.fit_transform(y)

In [35]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=object)

In [36]:
from sklearn.cross_validation import train_test_split

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=42)

In [38]:
x_train,x_test,y_train,y_test

(array([[1.00e+00, 0.00e+00, 0.00e+00, 4.40e+01, 7.20e+04],
        [1.00e+00, 0.00e+00, 0.00e+00, 4.80e+01, 7.90e+04],
        [0.00e+00, 1.00e+00, 0.00e+00, 3.00e+01, 5.40e+04],
        [1.00e+00, 0.00e+00, 0.00e+00, 3.70e+01, 6.70e+04],
        [0.00e+00, 1.00e+00, 0.00e+00, 4.00e+01, 6.85e+04],
        [0.00e+00, 0.00e+00, 1.00e+00, 3.80e+01, 6.10e+04],
        [0.00e+00, 0.00e+00, 1.00e+00, 3.25e+01, 5.20e+04]]),
 array([[0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
        [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
        [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04]]),
 array([0, 1, 0, 1, 1, 0, 0], dtype=object),
 array([0, 1, 1], dtype=object))

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
sc_x=StandardScaler()

In [41]:
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [42]:
x_train,x_test

(array([[ 1.15470054, -0.63245553, -0.63245553,  0.9522879 ,  0.8016378 ],
        [ 1.15470054, -0.63245553, -0.63245553,  1.64486092,  1.57946457],
        [-0.8660254 ,  1.58113883, -0.63245553, -1.47171767, -1.19848819],
        [ 1.15470054, -0.63245553, -0.63245553, -0.25971488,  0.24604724],
        [-0.8660254 ,  1.58113883, -0.63245553,  0.25971488,  0.41272441],
        [-0.8660254 , -0.63245553,  1.58113883, -0.08657163, -0.42066142],
        [-0.8660254 , -0.63245553,  1.58113883, -1.03885953, -1.42072441]]),
 array([[-0.8660254 ,  1.58113883, -0.63245553,  1.99114743,  2.02393701],
        [-0.8660254 , -0.63245553,  1.58113883, -1.99114743, -1.86519685],
        [ 1.15470054, -0.63245553, -0.63245553, -0.60600139, -0.75401575]]))